data:
  src_dataset_file: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/dataset_2000_hvg_src/normal.dataset"
  tgt_dataset_folder: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/dataset_2000_hvg_tgt"
  src_adata: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/h5ad_pairing_2000_hvg_src/normal.h5ad"
  tgt_adata_folder: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/h5ad_pairing_2000_hvg_tgt"
  cond_list: 
      - 'cell_type_cellgen_harm'

trainer:
  batch_size: 16
  use_count_decoder: true
  tgt_vocab_size: 20274
  d_model: 768
  d_condc: 64
  d_condt: 768
  generate: false
  layer_norm: true
  use_positional_encoding: false
  add_cell_time: true
  dropout: 0
  num_heads: 8
  num_layers: 6
  loss_mode: 'zinb'
  d_ff: 32
  max_seq_length: 666
  mask_scheduler: 'cosine'
  output_dir: './results/test'
  #ckpt_count_path: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/results/lps/count_interpolation_ourMED_ws_on2k_T_C_alltps/checkpoints/20250221_1130_cellgen_train_count_lr_0.001_wd_0.001_batch_16_zinb_tp_1-2-3_s_42_pos_time_pos_sin_m_cosine-epoch=03.ckpt"
  #ckpt_masking_path: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/results/lps/interpolation_2k_all_tps_cond_celltype/res/checkpoints/20250216_1825_cellgen_train_masking_lr_0.0001_wd_0.0001_batch_64_ptime_pos_sin_m_cosine_tp_1-2-3_s_42-epoch=15.ckpt"
  mapping_dict_path: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/token_id_to_genename_2000_hvg.pkl'
  tokenid_to_rowid_path: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/tokenid_to_rowid_2000_hvg.pkl'
  encoder: 'scmaskgit'
  encoder_path: '/lustre/scratch126/cellgen/team361/av13/scmaskgit/scmaskgit/output3/checkpoints/20250113_1104_cellgen_train_masking_lr_5e-05_wd_1e-06_batch_64_ptime_pos_sin_m_pow_tp_1-2-3_s_42-epoch=06.ckpt'
  context_mode: true
  temperature: 1
  iterations: 19
  pos_encoding_mode: 'time_pos_sin'
  exclude_src: true
  perturbation_mode: 'mask'
  genes_to_perturb:
    - 'ENSG00000125538'

  validation_mode: 'inference'
  perturbation_sequence:
    - 'tgt'
  var_list:
    - 'cell_type_cellgen_harm'
    - 'donor_cellgen_harm'
    - 'time_after_LPS'
  pred_tps:
    - 1
    - 2
    - 3
  pert_tps:
    - 1
  loss_mode: 'zinb'
  n_samples: 3

    
datamodule:
  batch_size: 16
  num_workers: 8
  shuffle: false
  split: false
  max_len: 666
  var_list:
    - 'cell_type_cellgen_harm'
    - 'donor_cellgen_harm'
    - 'time_after_LPS'
  pred_tps:
    - 1
    - 2
    - 3

model:
  precision: 16
  ckpt_masking_path: "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/results/lps/count_interpolation_ourMED_ws_on2k_T_C_alltps/checkpoints/20250221_1130_cellgen_train_count_lr_0.001_wd_0.001_batch_16_zinb_tp_1-2-3_s_42_pos_time_pos_sin_m_cosine-epoch=03.ckpt"
  
  #"/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/results/lps/count_interpolation_ourMED_ws_on2k_T_C_alltps/checkpoints/20250221_1130_cellgen_train_count_lr_0.001_wd_0.001_batch_16_zinb_tp_1-2-3_s_42_pos_time_pos_sin_m_cosine-epoch=03.ckpt"
  
  # "/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/results/lps/count_interpolation_ourMED_ws_on2k_T_C_alltps_ns3_withval/checkpoints/20250305_1812_cellgen_train_count_lr_0.001_wd_0.001_batch_16_zinb_tp_1-2-3_s_42_pos_time_pos_sin_m_cosine-epoch=03.ckpt"
  