data:
  tgt_dataset_folder: "T_perturb/T_perturb/pp/res/hspc_pbmc_median_inter_tissue_all/dataset_all_tgt"
  src_dataset_file: "T_perturb/T_perturb/pp/res/hspc_pbmc_median_inter_tissue_all/dataset_all_src/intermediate.dataset"
  src_adata_file: "T_perturb/T_perturb/pp/res/hspc_pbmc_median_inter_tissue_all/h5ad_pairing_all_src/intermediate.h5ad"
  tgt_adata_folder: "T_perturb/T_perturb/pp/res/hspc_pbmc_median_inter_tissue_all/h5ad_pairing_all_tgt"
  # cond_list:
  #   - 'celltype_v2'
  #   - 'diff_state'
  # filter_var: 'celltype_v2'
  # filter_cond:
  # - 'DC_pre'
  # - 'Mono_Pre'
  # - 'DC_pre'
  # - 'Macrophage'
  # perturb_genes_file: 'T_perturb/T_perturb/plt/res/hspc/pbmc_median/gene_embedding/20250312_gene_clusters_LMPP_L4.csv'
  # perturb_cluster:
  # - '75'

trainer:
  tgt_vocab_size: 17856
  d_model: 768
  num_heads: 8
  num_layers: 6
  d_ff: 64
  max_seq_length: 4096
  dropout: 0
  mask_scheduler: 'pow'
  output_dir: 'T_perturb/T_perturb/plt/res/hspc/pbmc_median/perturbation'
  mapping_dict_path: 'T_perturb/T_perturb/pp/res/hspc_pbmc_median_inter_tissue_all/token_id_to_genename_all.pkl'
  tokenid_to_rowid_path: 'T_perturb/T_perturb/pp/res/hspc_pbmc_median_inter_tissue_all/tokenid_to_rowid_all.pkl'
  encoder: 'scmaskgit'
  encoder_path: '/lustre/scratch126/cellgen/team361/av13/scmaskgit/scmaskgit/output3/checkpoints/20250113_1104_cellgen_train_masking_lr_5e-05_wd_1e-06_batch_64_ptime_pos_sin_m_pow_tp_1-2-3_s_42-epoch=06.ckpt'
  context_mode: False
  pos_encoding_mode: 'time_pos_sin'
  perturbation_mode: 'mask'
  genes_to_perturb:
    - 'GP1BB'
  validation_mode: 'inference'
  perturbation_sequence:
    - 'src'
  var_list:
    - 'sex'
    - 'phase'
    - 'tissue'
    - 'celltype_v2'
    - 'diff_state'
  pred_tps:
    - 1
  #count decoder
  use_count_decoder: true
  loss_mode: 'zinb'
  n_samples: 3

datamodule:
  batch_size: 64
  num_workers: 4
  shuffle: False
  split: False
  max_len: 4096
  var_list:
    - 'sex'
    - 'phase'
    - 'tissue'
    - 'celltype_v2'
    - 'diff_state'
  pred_tps:
    - 1
model:
  precision: 16
  ckpt_masking_path: "T_perturb/T_perturb/plt/res/hspc/pbmc_median/checkpoints/all_genes_inter_tissue_counts.ckpt/pytorch_model.bin"
