method: grid
metric:
  goal: minimize
  name: val/mse_epoch
name: tune_count
parameters:
  train_mode:
    value: 'count'
  split:
    value: True
  splitting_mode:
    value: 'stratified'
  epochs:
   value: 5
  ckpt_masking_path:
    value: '/lustre/scratch126/cellgen/lotfollahi/kl11/T_perturb/cytomeister/plt/res/lps/pbmc_median/interpolation/res/checkpoints/20250430_1657_cellgen_train_masking_lr_0.0001_wd_0.0001_batch_64_ptime_pos_sin_m_pow_tp_1-3_s_42-epoch=19.ckpt'
  output_dir:
    value: 'T_perturb/cytomeister/plt/res/lps/pbmc_median/sweep'
  src_dataset:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/tokenized_data2k_hvg_ourMED_all_tps/dataset_2000_hvg_src/normal.dataset'
  tgt_dataset_folder:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/tokenized_data2k_hvg_ourMED_all_tps/dataset_2000_hvg_tgt'
  src_adata:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/tokenized_data2k_hvg_ourMED_all_tps/h5ad_pairing_2000_hvg_src/normal.h5ad'
  tgt_adata_folder:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/tokenized_data2k_hvg_ourMED_all_tps/h5ad_pairing_2000_hvg_tgt'
  max_len:
    value: 666
  tgt_vocab_size:
    value: 1990
  cellgen_lr:
    value: 0.0001
  cellgen_wd:
    value: 0.0001
  cond_list:
    value: 'time_after_LPS'
  num_layers:
    value: 6
  d_ff:
    value: 32
  loss_mode:
    value: 'zinb'
  count_dropout:
    values: [0.0, 0.05, 0.1]
  count_lr:
    values: [0.001, 0.0005, 0.0001]
  count_wd:
    values: [0.0005,0.0001, 0.00005]
  batch_size:
    values: [64, 128]
program: /lustre/scratch126/cellgen/lotfollahi/kl11/T_perturb/cytomeister/train.py
project: ttransformer_sweep
