method: grid
metric:
  goal: minimize
  name: test/emd
name: tune_generate
parameters:
  test_mode:
    value: 'count'
  split:
    value: False
  ckpt_count_path:
    value: './T_perturb/cytomeister/Model/checkpoints/20240519_1627_Tcell_interpol_Encoder_5e-05_wd_0.01_batch_64_zinb_tp_1-3-epoch=19.ckpt'
  generate:
    value: True
  max_len:
    value: 300
  tgt_vocab_size:
    value: 1261
  condition_keys:
    value: 'Cell_culture_batch'
  mode:
    value: 'Transformer_encoder'
  num_layers:
    value: 6
  d_ff:
    value: 128
  petra_lr:
    value: 0.0001
  petra_wd:
    value: 0.0001
  count_lr:
    value: 0.00005
  count_wd:
    value: 0.0001
  batch_size:
    value: 64
  iterations:
    value: 19
  loss_mode:
    value: 'zinb'
  output_dir:
    value: './T_perturb/cytomeister/plt/res/cytoimmgen'
  src_dataset:
    value: './T_perturb/tokenized_datacytoimmgen/dataset_hvg_src_transformer/0h.dataset'
  tgt_dataset_folder:
    value: './T_perturb/tokenized_datacytoimmgen/dataset_hvg_tgt'
  src_adata:
    value: './T_perturb/tokenized_datacytoimmgen/h5ad_pairing_hvg_src/0h.h5ad'
  tgt_adata_folder:
    value: './T_perturb/tokenized_datacytoimmgen/h5ad_pairing_hvg_tgt'
  mask_scheduler:
    values: ['pow', 'exp', 'cosine']
  temperature:
    values: [1.0, 1.25, 1.5, 2.0]
program: /lustre/scratch123/hgi/projects/healthy_imm_expr/t_generative/T_perturb/cytomeister/val.py
project: ttransformer_sweep
