# masking attention
method: grid
metric:
  goal: minimize
  name: val/perplexity_epoch
name: tune_masking_lps
parameters:
  train_mode:
    value: 'masking'
  split:
    value: True
  splitting_mode:
    value: stratified
  epochs:
   value: 10
  output_dir:
    value: 'T_perturb/T_perturb/plt/res/lps/pbmc_median/sweep'
  src_dataset:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/dataset_2000_hvg_src/normal.dataset'
  tgt_dataset_folder:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/dataset_2000_hvg_tgt'
  src_adata:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/h5ad_pairing_2000_hvg_src/normal.h5ad'
  tgt_adata_folder:
    value: '/lustre/scratch126/cellgen/team298/dv8/trace_paper/trace_final/T_perturb/T_perturb/pp/res/2k_hvg_ourMED_all_tps/h5ad_pairing_2000_hvg_tgt'
  max_len:
    value: 666
  tgt_vocab_size:
    value: 1990
  n_workers:
    value: 4
  mask_scheduler:
    value: 'pow'
  cond_list:
    value: 'time_after_LPS'
  pos_encoding_mode:
    value: 'time_pos_sin'
  num_layers:
    value: 6
  batch_size:
    value: 64
  d_ff:
    values: [32, 64]
  encoder:
    value: 'scmaskgit'
  context_mode:
    value: True
  encoder_path:
    value: '/lustre/scratch126/cellgen/team361/av13/scmaskgit/scmaskgit/output3/checkpoints/20250113_1104_cellgen_train_masking_lr_5e-05_wd_1e-06_batch_64_ptime_pos_sin_m_pow_tp_1-2-3_s_42-epoch=06.ckpt'
  d_model:
    value: 768
  # num_layers:
  #   values: [6]
  # batch_size:
  #   values: [64, 128, 256]
  cellgen_lr:
    values: [0.00001, 0.00005, 0.0001, 0.0005]
  # d_ff:
  #   values: [64, 128]
  cellgen_wd:
    values: [0.00005, 0.0001, 0.0005]
  # petra_lr:
  #   distribution: log_uniform
  #   min: 0.00001
  #   max: 0.001

  # dropout:
  #   distribution: uniform
  #   low: 0.1
  #   high: 0.5
  # batch_size:
  #   value: 256
program: /lustre/scratch126/cellgen/lotfollahi/kl11/T_perturb/cytomeister/train.py
project: ttransformer_sweep
