data:
  src_dataset_file: "T_perturb/tokenized_data/hspc_pbmc_median_inter_tissue_all_tf/dataset_5000_hvg_src/intermediate.dataset"
  tgt_dataset_folder: "T_perturb/tokenized_data/hspc_pbmc_median_inter_tissue_all_tf/dataset_5000_hvg_tgt"
  src_adata_file: "T_perturb/tokenized_data/hspc_pbmc_median_inter_tissue_all_tf/h5ad_pairing_5000_hvg_src/intermediate.h5ad"
  tgt_adata_folder: "T_perturb/tokenized_data/hspc_pbmc_median_inter_tissue_all_tf/h5ad_pairing_5000_hvg_tgt"
trainer:
  tgt_vocab_size: 5685
  d_model: 768
  num_heads: 8
  num_layers: 6
  d_ff: 64
  max_seq_length: 2275
  dropout: 0
  mask_scheduler: 'pow'
  output_dir: 'T_perturb/res/hspc/perturbation'
  mapping_dict_path: 'T_perturb/tokenized_data/hspc_pbmc_median_inter_tissue_all_tf/token_id_to_genename_5000_hvg.pkl'
  tokenid_to_rowid_path: 'T_perturb/tokenized_data/hspc_pbmc_median_inter_tissue_all_tf/tokenid_to_rowid_5000_hvg.pkl'
  encoder: 'scmaskgit'
  context_mode: False
  pos_encoding_mode: 'time_pos_sin'
  perturbation_mode: 'mask'
  return_attn: false
  genes_to_perturb:
    - {{PERTURBED_GENE}}
  perturbation_token: 1
  validation_mode: 'inference'
  perturbation_sequence:
    - 'src'
  var_list:
    - 'sex'
    - 'phase'
    - 'tissue'
    - 'celltype_v2'
    - 'diff_state'
  pred_tps:
    - 1

datamodule:
  batch_size: 32
  num_workers: 8
  context_tps: [2]
  shuffle: False
  split: False
  max_len: 2200
  var_list:
    - 'sex'
    - 'phase'
    - 'tissue'
    - 'celltype_v2'
    - 'diff_state'
  pred_tps:
    - 1
model:
  ckpt_masking_path: "T_perturb/res/hspc/ddings/res/checkpoints/20241114_1146_cellgen_train_masking_lr_1e-05_wd_1e-05_batch_64_ptime_pos_learnt_m_cosine_tp_1-2_s_42-epoch=09.ckpt"
