data:
  src_dataset_file: "T_perturb/tokenized_data/LPS_all_tps_2k/dataset_2000_hvg_src/normal.dataset"
  tgt_dataset_folder: "T_perturb/tokenized_data/LPS_all_tps_2k/dataset_2000_hvg_tgt"
  src_adata: "T_perturb/tokenized_data/LPS_all_tps_2k/h5ad_pairing_2000_hvg_src/normal.h5ad"
  tgt_adata_folder: "T_perturb/tokenized_data/LPS_all_tps_2k/h5ad_pairing_2000_hvg_tgt"
  cond_list:
    - "cell_type_harmonized"

trainer:
  use_count_decoder: true
  n_samples: 3
  tgt_vocab_size: 2002
  d_model: 768
  generate: false
  use_positional_encoding: false
  dropout: 0
  num_heads: 8
  num_layers: 6
  loss_mode: "zinb"
  d_ff: 32
  max_seq_length: 797
  mask_scheduler: "cosine"
  output_dir: "T_perturb/res/perturbation"
  mapping_dict_path: "T_perturb/tokenized_data/LPS_all_tps_2k/token_id_to_genename_2000_hvg.pkl"
  tokenid_to_rowid_path: "T_perturb/tokenized_data/LPS_all_tps_2k/tokenid_to_rowid_2000_hvg.pkl"
  encoder: "scmaskgit"
  encoder_path: "Perturbgen/pretraining_cohort/20250709_1223_cellgen_train_masking_lr_5e-05_wd_1e-06_batch_64_ptime_pos_sin_m_pow_tp_1-2-3_s_42-epoch=00.ckpt"
  context_mode: false
  temperature: 1.5
  iterations: 19
  pos_encoding_mode: "time_pos_sin"
  exclude_src: false
  perturbation_mode: "mask"
  genes_to_perturb:
    - "ENSG00000125538" # or gene name to perturb
  validation_mode: "inference"
  perturbation_sequence:
    - "src"
  var_list:
    - "cell_type_harmonized"
    - "cell_pairing_index"
    - "time_after_LPS"
  pred_tps:
    - 1
    - 2


datamodule:
  batch_size: 64
  num_workers: 8
  shuffle: false
  split: false
  max_len: 797
  var_list:
    - "cell_type_harmonized"
    - "time_after_LPS"
    - "cell_pairing_index"
  pred_tps:
    - 1
    - 2

model:
  precision: 16
  ckpt_masking_path: "path/to/count_decoder_checkpoint.ckpt" 
