method: grid
metric:
  goal: minimize
  name: val/mse_epoch
name: tune_count
parameters:
  train_mode:
    value: 'count'
  split:
    value: True
  splitting_mode:
    value: 'stratified'
  epochs:
   value: 5
  ckpt_masking_path:
    value: 'T_perturb/T_perturb/plt/res/cytoimmgen/pbmc_median/interpolation/checkpoints/20250430_0802_cellgen_train_masking_lr_1e-05_wd_1e-05_batch_64_ptime_pos_sin_m_pow_tp_1-3_s_42-epoch=19.ckpt'
  output_dir:
    value: 'T_perturb/T_perturb/plt/res/cytoimmgen/pbmc_median/sweep'
  src_dataset:
    value: 'T_perturb/T_perturb/pp/res/cytoimmgen_pbmc_median/dataset_2000_hvg_src/0h.dataset'
  tgt_dataset_folder:
    value: 'T_perturb/T_perturb/pp/res/cytoimmgen_pbmc_median/dataset_2000_hvg_tgt'
  src_adata:
    value: 'T_perturb/T_perturb/pp/res/cytoimmgen_pbmc_median/h5ad_pairing_2000_hvg_src/0h.h5ad'
  tgt_adata_folder:
    value: 'T_perturb/T_perturb/pp/res/cytoimmgen_pbmc_median/h5ad_pairing_2000_hvg_tgt'
  max_len:
    value: 400
  tgt_vocab_size:
    value: 1360
  condition_keys:
    value: 'Cell_culture_batch'
  cellgen_lr:
    value: 0.0001
  cellgen_wd:
    value: 0.0001
  num_layers:
    value: 6
  d_ff:
    value: 64
  loss_mode:
    value: 'zinb'
  count_lr:
    values: [0.001, 0.005, 0.001]
  count_wd:
    values: [0.005, 0.001, 0.0005, 0.0001]
  batch_size:
    values: [64, 128, 256]
program: /lustre/scratch123/hgi/projects/healthy_imm_expr/t_generative/T_perturb/T_perturb/train.py
project: ttransformer_sweep
