# masking attention
method: grid
metric:
  goal: minimize
  name: val/mse_epoch
name: tune_eb_count
parameters:
  train_mode:
    value: 'count'
  split:
    value: True
  splitting_mode:
    value: random
  epochs:
    value: 20
  output_dir:
    value: './T_perturb/T_perturb/plt/res/eb'
  src_dataset:
    value: './T_perturb/T_perturb/pp/res/eb/dataset_hvg_src/Day 00-03.dataset'
  tgt_dataset_folder:
    value: './T_perturb/T_perturb/pp/res/eb/dataset_hvg_tgt'
  src_adata:
    value: './T_perturb/T_perturb/pp/res/eb/h5ad_pairing_hvg_src/Day 00-03.h5ad'
  tgt_adata_folder:
    value: './T_perturb/T_perturb/pp/res/eb/h5ad_pairing_hvg_tgt'
  batch_size:
    value: 32
  max_len:
    value: 263
  tgt_vocab_size:
    value: 2001
  var_list:
    value: 'Time_point'
  petra_lr:
    value: 0.0001
  d_ff:
    value: 16
  num_layers:
    value: 2
  count_lr:
    values: [0.0001, 0.00005, 0.00001]
  count_wd:
    values: [0.01, 0.001, 0.0001]
  count_dropout:
    values: [0.0, 0.1, 0.25]
  # Example of a log_uniform distribution, if needed, uncomment and modify appropriately
  # petra_lr:
  #   distribution: log_uniform
  #   min: 0.00001
  #   max: 0.001
  # Example of a uniform distribution, if needed, uncomment and modify appropriately
  # batch_size:
  #   distribution: uniform
  #   low: 0.1
  #   high: 0.5
program: /lustre/scratch123/hgi/projects/healthy_imm_expr/t_generative/T_perturb/T_perturb/train.py
project: ttransformer_sweep
