# masking attention
method: grid
metric:
  goal: minimize
  name: val/perplexity_epoch
name: tune_masking
parameters:
  train_mode:
    value: 'masking'
  split:
    value: True
  splitting_mode:
    value: stratified
  epochs:
   value: 5
  output_dir:
    value: './T_perturb/T_perturb/iclr/cytoimmgen/sweep/res/checkpoints'
  src_dataset:
    value: "./T_perturb/T_perturb/pp/res/cytoimmgen/dataset_hvg_src/0h.dataset"
  tgt_dataset_folder:
    value: "./T_perturb/T_perturb/pp/res/cytoimmgen/dataset_hvg_tgt"
  src_adata:
    value: "./T_perturb/T_perturb/pp/res/cytoimmgen/h5ad_pairing_hvg_src/0h.h5ad"
  tgt_adata_folder:
    value: "./T_perturb/T_perturb/pp/res/cytoimmgen/h5ad_pairing_hvg_tgt"
  max_len:
    value: 300
  tgt_vocab_size:
    value: 20274
  condition_keys:
    value: 'Cell_culture_batch'
  mask_scheduler:
    value: 'cosine'
  positional_encoding:
    value: 'time_pos_sin'
  num_layers:
    values: [6]
  batch_size:
    values: [64, 128, 256]
  cellgen_lr:
    values: [0.0001, 0.00001, 0.001]
  d_ff:
    values: [64, 128]
  cellgen_wd:
    values: [0.0001, 0.00001, 0.001]

  # petra_lr:
  #   distribution: log_uniform
  #   min: 0.00001
  #   max: 0.001

  # dropout:
  #   distribution: uniform
  #   low: 0.1
  #   high: 0.5
  # batch_size:
  #   value: 256
program: /lustre/scratch123/hgi/projects/healthy_imm_expr/t_generative/T_perturb/T_perturb/train.py
project: ttransformer_sweep
