method: grid
metric:
  goal: minimize
  name: val/mse_epoch
name: tune_count
parameters:
  train_mode:
    value: 'count'
  split:
    value: True
  splitting_mode:
    value: 'stratified'
  epochs:
   value: 20
  output_dir:
    value: './T_perturb/T_perturb/plt/res/cytoimmgen'
  src_dataset:
    value: './T_perturb/T_perturb/pp/res/cytoimmgen/dataset_hvg_src/0h.dataset'
  tgt_dataset_folder:
    value: './T_perturb/T_perturb/pp/res/cytoimmgen/dataset_hvg_tgt'
  src_adata:
    value: './T_perturb/T_perturb/pp/res/cytoimmgen/h5ad_pairing_hvg_src/0h.h5ad'
  tgt_adata_folder:
    value: './T_perturb/T_perturb/pp/res/cytoimmgen/h5ad_pairing_hvg_tgt'
  max_len:
    value: 300
  tgt_vocab_size:
    value: 1261
  condition_keys:
    value: 'Cell_culture_batch'
  petra_lr:
    value: 0.0001
  petra_wd:
    value: 0.0001
  num_layers:
    value: 6
  d_ff:
    value: 128
  mlm_prob:
    value: 0.15
  loss_mode:
    value: 'zinb'
  count_lr:
    values: [0.00005, 0.0001, 0.005]
  count_wd:
    values: [0.01, 0.005, 0.001]
  batch_size:
    value: 64
program: /lustre/scratch123/hgi/projects/healthy_imm_expr/t_generative/T_perturb/T_perturb/train.py
project: ttransformer_sweep
