# masking attention
method: grid
metric:
  goal: minimize
  name: val/perplexity_epoch
name: tune_masking_eb
parameters:
  train_mode:
    value: 'masking'
  split:
    value: True
  splitting_mode:
    value: random
  epochs:
   value: 20
  output_dir:
    value: './T_perturb/T_perturb/iclr/eb/sweep'
  src_dataset:
    value: './T_perturb/T_perturb/pp/res/eb/dataset_hvg_subsetted_src/Day 00-03.dataset'
  tgt_dataset_folder:
    value: './T_perturb/T_perturb/pp/res/eb/dataset_hvg_subsetted_tgt'
  src_adata:
    value: './T_perturb/T_perturb/pp/res/eb/h5ad_pairing_hvg_src/Day 00-03.h5ad'
  tgt_adata_folder:
    value: './T_perturb/T_perturb/pp/res/eb/h5ad_pairing_hvg_tgt'
  max_len:
    value: 270
  tgt_vocab_size:
    value: 1730
  var_list:
    value: 'Time_point'
  positional_encoding:
    value: 'sin_learnt'
  mask_scheduler:
    value: 'cosine'
  batch_size:
    values: [64]
  cellgen_lr:
    values: [0.001, 0.0001, 0.00001]
  num_layers:
    values: [1, 2, 3]
  d_ff:
    values: [16, 32]
  cellgen_wd:
    values: [0.001, 0.0001, 0.00001]

  # petra_lr:
  #   distribution: log_uniform
  #   min: 0.00001
  #   max: 0.001
    # distribution: uniform
    # low: 0.1
    # high: 0.5
  # batch_size:
  #   value: 256
program: /lustre/scratch123/hgi/projects/healthy_imm_expr/t_generative/T_perturb/T_perturb/train.py
project: ttransformer_sweep
